/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HubIndicator {
    'schema': string;
    'url': string;
  }
  interface HubIndicatorAttributes extends StencilHTMLAttributes {
    'schema'?: string;
    'url'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HubIndicator': Components.HubIndicator;
  }

  interface StencilIntrinsicElements {
    'hub-indicator': Components.HubIndicatorAttributes;
  }


  interface HTMLHubIndicatorElement extends Components.HubIndicator, HTMLStencilElement {}
  var HTMLHubIndicatorElement: {
    prototype: HTMLHubIndicatorElement;
    new (): HTMLHubIndicatorElement;
  };

  interface HTMLElementTagNameMap {
    'hub-indicator': HTMLHubIndicatorElement
  }

  interface ElementTagNameMap {
    'hub-indicator': HTMLHubIndicatorElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
